version: '3'

services:
  meal-prep-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - meal_prep_data:/var/lib/postgresql/data/

volumes:
  meal_prep_data:
